# Generated by Django 5.0.4 on 2024-04-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksi_store', '0012_auto_20210428_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default='!!', upload_to='ksi_store/'),
        ),
    ]
