# Generated by Django 5.0.4 on 2024-04-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksi_store', '0013_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='img',
            field=models.ImageField(default='!!', upload_to='ksi_store/'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='img',
            field=models.ImageField(default='!!', upload_to='ksi_store/'),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='img',
            field=models.ImageField(default='!!', upload_to='ksi_store/'),
        ),
        migrations.AlterField(
            model_name='household',
            name='img',
            field=models.ImageField(default='!!', upload_to='ksi_store/'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='img',
            field=models.ImageField(default='!!', upload_to='ksi_store/'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='img',
            field=models.ImageField(default='!!', upload_to='ksi_store/'),
        ),
    ]
